/* eslint-disable camelcase */

// used https://github.com/benkeen/generatedata to generate some of the dummy data.
//
export const DATABASE: {
  projects: Partial<Project>[],
  relations: Partial<Relation>[],
  tasks: Partial<PlanningTask>[],
  documents: Partial<AttachedDocument>[],
  resources: Partial<Resource>[],
  timesheets: Partial<Timesheet>[],
  worktypes: Array<{
    worktype_id: any,
    worktype_code: string,
    worktype_name: string,
  }>,
} = {
  projects: [
    {
      install_id: null,
      project_id: 1,
      project_number: 'A210001',
      project_description: '',
      relation_id: 1,
      status_name: 'order',
      price: 100,
      date_start: new Date(2021, 1),
      date_finish: new Date(2021, 6),
      notes: 'Our first project.',
      sales_manager_id: 1,
      project_manager_id: 2,
      project_engineer_id: 3,
    },
  ],
  relations: [
    {
      relation_id: 1,
      relation_type: 'customer',
      default_contactperson_id: 11,
      relation_first_name: null,
      relation_name: 'Morbi Tristique Senectus Corporation',
      relation_address: '4112 Arcu. Street',
      relation_zip: '2163',
      relation_city: 'Puri',
      relation_country: 'Canada',
      relation_email_1: 'nunc.ullamcorper@companyname.com',
      relation_phone_1: '(408) 788-7629',
    },
    {
      relation_id: 2,
      relation_type: 'customer',
      default_contactperson_id: 12,
      relation_first_name: null,
      relation_name: 'Sed Sapien Nunc Institute',
      relation_address: 'Ap #828-5449 Est. Road',
      relation_zip: '67-163',
      relation_city: 'Dublin',
      relation_country: 'Ireland',
      relation_email_1: 'nec.ante@companyname.com',
      relation_phone_1: '(650) 788-1089',
    },
    {
      relation_id: 3,
      relation_type: 'customer',
      default_contactperson_id: 13,
      relation_first_name: null,
      relation_name: 'Felis Eget Corp.',
      relation_address: '860-3917 Dictum Avenue',
      relation_zip: '24-193',
      relation_city: 'Weißenfels',
      relation_country: 'Austria',
      relation_email_1: 'tempus@companyname.com',
      relation_phone_1: '(555) 310-6214',
    },
    {
      relation_id: 4,
      relation_type: 'customer',
      default_contactperson_id: 14,
      relation_first_name: null,
      relation_name: 'Non Lobortis Quis Foundation',
      relation_address: 'Ap #158-9538 Magna. Road',
      relation_zip: '16143',
      relation_city: 'Kotli',
      relation_country: 'Canada',
      relation_email_1: 'aliquam.gravida.mauris@companyname.com',
      relation_phone_1: '1-976-426-5339',
    },
    {
      relation_id: 5,
      relation_type: 'customer',
      default_contactperson_id: 15,
      relation_first_name: null,
      relation_name: 'Est Nunc Corp.',
      relation_address: 'Ap #175-9185 Mus. Rd.',
      relation_zip: '11286',
      relation_city: 'Gdańsk',
      relation_country: 'Poland',
      relation_email_1: 'ac@companyname.com',
      relation_phone_1: '(714) 236-8508',
    },
    {
      relation_id: 6,
      relation_type: 'customer',
      default_contactperson_id: 16,
      relation_first_name: null,
      relation_name: 'Cras Eu Corp.',
      relation_address: '508-5721 Penatibus St.',
      relation_zip: '21299',
      relation_city: 'Marbella',
      relation_country: 'Mexico',
      relation_email_1: 'amet.dapibus.id@companyname.com',
      relation_phone_1: '1-268-458-2802',
    },
    {
      relation_id: 7,
      relation_type: 'customer',
      default_contactperson_id: 17,
      relation_first_name: null,
      relation_name: 'Cras Dolor Dolor Industries',
      relation_address: 'Ap #635-3760 Vitae Rd.',
      relation_zip: '57411',
      relation_city: 'Gwangju',
      relation_country: 'Indonesia',
      relation_email_1: 'in@companyname.com',
      relation_phone_1: '(521) 122-7848',
    },
    {
      relation_id: 8,
      relation_type: 'customer',
      default_contactperson_id: 18,
      relation_first_name: null,
      relation_name: 'Mollis Vitae Posuere Corporation',
      relation_address: 'Ap #247-6180 Euismod St.',
      relation_zip: '58970',
      relation_city: 'Chonchi',
      relation_country: 'India',
      relation_email_1: 'eu.neque@companyname.com',
      relation_phone_1: '1-302-376-7678',
    },
    {
      relation_id: 9,
      relation_type: 'customer',
      default_contactperson_id: 19,
      relation_first_name: null,
      relation_name: 'Ut Semper PC',
      relation_address: 'P.O. Box 508, 3446 Ultrices Rd.',
      relation_zip: '20708',
      relation_city: 'Amsterdam',
      relation_country: 'Netherlands',
      relation_email_1: 'at.libero@companyname.com',
      relation_phone_1: '(684) 436-6726',
    },
    {
      relation_id: 10,
      relation_type: 'customer',
      default_contactperson_id: 20,
      relation_first_name: null,
      relation_name: 'Nulla Facilisi Industries',
      relation_address: 'Ap #122-6625 Egestas Avenue',
      relation_zip: '1415',
      relation_city: 'Vinh',
      relation_country: 'Singapore',
      relation_email_1: 'cursus@companyname.com',
      relation_phone_1: '1-498-962-7689',
    },
    {
      relation_id: 11,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Ingrid',
      relation_name: 'Morris',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Puri',
      relation_country: 'Canada',
      relation_email_1: 'nunc.ullamcorper@companyname.com',
      relation_phone_1: '(408) 788-7629',
    },
    {
      relation_id: 12,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Kuame',
      relation_name: 'Hunter',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Dublin',
      relation_country: 'Ireland',
      relation_email_1: 'nec.ante@companyname.com',
      relation_phone_1: '(650) 788-1089',
    },
    {
      relation_id: 13,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Allegra',
      relation_name: 'Witt',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Weißenfels',
      relation_country: 'Austria',
      relation_email_1: 'tempus@companyname.com',
      relation_phone_1: '(555) 310-6214',
    },
    {
      relation_id: 14,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Vladimir',
      relation_name: 'Morgan',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Kotli',
      relation_country: 'Canada',
      relation_email_1: 'aliquam.gravida.mauris@companyname.com',
      relation_phone_1: '1-976-426-5339',
    },
    {
      relation_id: 15,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Faith',
      relation_name: 'Beck',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Gdańsk',
      relation_country: 'Poland',
      relation_email_1: 'ac@companyname.com',
      relation_phone_1: '(714) 236-8508',
    },
    {
      relation_id: 16,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Eliana',
      relation_name: 'Hogan',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Marbella',
      relation_country: 'Mexico',
      relation_email_1: 'amet.dapibus.id@companyname.com',
      relation_phone_1: '1-268-458-2802',
    },
    {
      relation_id: 17,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Madison',
      relation_name: 'Howe',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Gwangju',
      relation_country: 'Indonesia',
      relation_email_1: 'in@companyname.com',
      relation_phone_1: '(521) 122-7848',
    },
    {
      relation_id: 18,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Hollee',
      relation_name: 'Eaton',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Chonchi',
      relation_country: 'India',
      relation_email_1: 'eu.neque@companyname.com',
      relation_phone_1: '1-302-376-7678',
    },
    {
      relation_id: 19,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Zoe',
      relation_name: 'Levine',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Amsterdam',
      relation_country: 'Netherlands',
      relation_email_1: 'at.libero@companyname.com',
      relation_phone_1: '(684) 436-6726',
    },
    {
      relation_id: 20,
      relation_type: 'contactperson',
      default_contactperson_id: null,
      relation_first_name: 'Aline',
      relation_name: 'Davidson',
      relation_address: null,
      relation_zip: null,
      relation_city: 'Vinh',
      relation_country: 'Singapore',
      relation_email_1: 'cursus@companyname.com',
      relation_phone_1: '1-498-962-7689',
    },
  ],
  tasks: [
    {
      task_id: '',
      parent_id: null,
      project_id: '',
      task_description: '',
      date_start: null,
      date_start_actual: null,
      date_finish: null,
      date_finish_actual: null,
      date_delivery: null,
    },
  ],
  documents: [
    {
      project_id: '',
      title: '',
      version: null,
      is_hidden: null,
      path: '',
      size: null,
      date_created: '',
      date_modified: '',
    },
  ],
  resources: [
    {
      resource_id: 1,
      resource_first_name: 'Alexis',
      resource_name: 'Pollard',
      resource_email_1: 'consequat.lectus@peazy.com',
      resource_phone_1: '1-455-263-6925',
    },
    {
      resource_id: 2,
      resource_first_name: 'Jerome',
      resource_name: 'Berry',
      resource_email_1: 'enim.mauris@peazy.com',
      resource_phone_1: '(375) 841-1174',
    },
    {
      resource_id: 3,
      resource_first_name: 'Arsenio',
      resource_name: 'Miles',
      resource_email_1: 'molestie@peazy.com',
      resource_phone_1: '1-425-952-7232',
    },
    {
      resource_id: 4,
      resource_first_name: 'Delilah',
      resource_name: 'Beasley',
      resource_email_1: 'quisque.porttitor@peazy.com',
      resource_phone_1: '(725) 904-0825',
    },
    {
      resource_id: 5,
      resource_first_name: 'Cadman',
      resource_name: 'Gonzalez',
      resource_email_1: 'mauris.ipsum.porta@peazy.com',
      resource_phone_1: '(537) 390-9339',
    },
    {
      resource_id: 6,
      resource_first_name: 'Connor',
      resource_name: 'Gonzalez',
      resource_email_1: 'lorem.ipsum@peazy.com',
      resource_phone_1: '(823) 242-8392',
    },
    {
      resource_id: 7,
      resource_first_name: 'David',
      resource_name: 'Luna',
      resource_email_1: 'vel.arcu@peazy.com',
      resource_phone_1: '(623) 216-5785',
    },
    {
      resource_id: 8,
      resource_first_name: 'Aimee',
      resource_name: 'Sims',
      resource_email_1: 'aliquet.phasellus@peazy.com',
      resource_phone_1: '1-482-304-2164',
    },
    {
      resource_id: 9,
      resource_first_name: 'Knox',
      resource_name: 'Rodriquez',
      resource_email_1: 'libero.lacus@peazy.com',
      resource_phone_1: '1-498-221-7726',
    },
    {
      resource_id: 10,
      resource_first_name: 'Cruz',
      resource_name: 'Bright',
      resource_email_1: 'ut@peazy.com',
      resource_phone_1: '(553) 314-0172',
    },
  ],
  timesheets: [
    {
      project_id: '',
      resource_id: '',
      worktype_id: '',
      date_start: '',
      date_end: '',
      amount: 0,
      rate_internal: 0,
    },
  ],
  worktypes: [
    {
      worktype_id: '',
      worktype_code: '',
      worktype_name: '',
    },
  ],
};